### PR TITLE
Uncomment code to ensure relay version matches origin

### PR DESCRIPTION
**Pull request by Fluxx**
I looked into #20 and tests still pass, so I'm going to call this not an issue until it comes up again.

### CODE REVIEW

**Comment by Fluxx** [comment]
Oh weird somehow my tests passed locally the first time, but now they do not and I get the same exception as CI so will fix.

**Comment by fuziontech** [comment]
:+1:

**Comment by tkaemming** [comment]
This seems reasonable to me, although it would be nice if there was a test for this (or at least an enhancement ticket to add one.)

**Comment by Fluxx** [comment]
Ticket to add test added in #29.

**Pull request merged**
